
let products = [
  {
    id: "1",
    nombre: "Calabresa",
    precio: "1950",
    descripcion:
      "Pizza de Muzzarella, Longaniza Calabresa, Morrones, Salsa de Tomate, Condimentos y Aceitunas Verdes.",
    imagen: "https://i.ibb.co/27zLq3m/Calabresa.png",
    categoria: "Pizzas",
  },
  {
    id: "2",
    nombre: "Especial",
    precio: "2400",
    descripcion:
      "Pizza de Muzzarella, Jamon Natural, Morrones , Salsa de Tomate, Condimentos y Aceitunas Verdes.",
    imagen: "https://i.ibb.co/5cn3fQW/Especial.png",
    categoria: "Pizzas",
  },
  {
    id: "3",
    nombre: "Fugazza",
    precio: "1250",
    descripcion:
      "Pizza de Cebolla, Condimentos y Aceitunas Verdes. (sin Quesos)",
    imagen: "https://i.ibb.co/MV4TzFG/Fugazza.png",
    categoria: "Pizzas",
  },
  {
    id: "4",
    nombre: "Muzza y jamon",
    precio: "2300",
    descripcion:
      "Pizza de Muzzarella, Jamon Natural, Salsa de Tomate, Condimentos y Aceitunas Verdes.",
    imagen: "https://i.ibb.co/Dz9H9kr/Muzza-y-jamon.png",
    categoria: "Pizzas",
  },
  {
    id: "5",
    nombre: "Muzza y Morron",
    precio: "1800",
    descripcion:
      "Pizza de Muzzarella, Morrones, Salsa de Tomate, Condimentos y Aceitunas Verdes.",
    imagen: "https://i.ibb.co/Qjn7RSP/Muzza-y-Morron.png",
    categoria: "Pizzas",
  },
  {
    id: "6",
    nombre: "Muzzarella",
    precio: "1300",
    descripcion:
      "Pizza de Muzzarella, Salsa de Tomate, Condimentos y Aceitunas Verdes.",
    imagen: "https://i.ibb.co/x8XQjc6/Muzzarella.png",
    categoria: "Pizzas",
  },
  {
    id: "7",
    nombre: "Napolitana",
    precio: "2100",
    descripcion: "Pizza de Muzzarella, Salsa de Tomate, Tomate en rodajas, Condimentos y Aceitunas Verdes.",
    imagen: "https://i.ibb.co/KWkdgB7/napo.png",
    categoria: "Pizzas",
  },
  {
    id: "8",
    nombre: "Fugazzetta",
    precio: "2100",
    descripcion: "Pizza de Muzzarella, Cebolla, Condimentos y Aceitunas Verdes.",
    imagen: "https://i.ibb.co/MV4TzFG/Fugazza.png",
    categoria: "Pizzas",
  },
  {
    id: "9",
    nombre: "Anana",
    precio: "3550",
    descripcion: "Pizza de Muzzarella, Anana, Cerezas al Maraschino, Jamon Natural, Salsa de Tomate, Condimentos y Aceitunas Verdes.",
    imagen: "https://i.ibb.co/qm8zk3w/anana.png",
    categoria: "Pizzas",
  },
  {
    id: "10",
    nombre: "Americana (anchoas)",
    precio: "2350",
    descripcion: "Pizza de Muzzarella, Anchoas, Morrones, Salsa de Tomate, Condimentos y Aceitunas Verdes.",
    imagen: "https://i.ibb.co/N9rpSgb/americana.png",
    categoria: "Pizzas",
  },
  {
    id: "11",
    nombre: "Anchoas",
    precio: "2100",
    descripcion: "Pizza de Anchoas, Morrones, Salsa de Tomate, Condimentos y Aceitunas Verdes.",
    imagen: "https://i.ibb.co/G5PKsJ6/anchoas.png",
    categoria: "Pizzas",
  },
  {
    id: "12",
    nombre: "Jamon con Huevo",
    precio: "2400",
    descripcion: "Pizza de Muzzarella, Jamon Natural, Huevo Duro, Salsa de Tomate, Condimentos y Aceitunas Verdes.",
    imagen: "https://i.ibb.co/dBsDQ04/jamonyhuevo.png",
    categoria: "Pizzas",
  },
  {
    id: "13",
    nombre: "Capresse",
    precio: "2300",
    descripcion: "Pizza de Muzzarella, Tomate en Rodajas, Albahaca, Salsa de Tomate, Condimentos y Aceitunas Verdes.",
    imagen: "https://i.ibb.co/DMh5t6n/capresse.png",
    categoria: "Pizzas",
  },
  {
    id: "14",
    nombre: "Carusso",
    precio: "2400",
    descripcion: "Pizza de Muzzarella, Tomate en Rodajas, Morrones, Provolone, Salsa de Tomate, Condimentos y Aceitunas Verdes.",
    imagen: "https://i.ibb.co/RDtt96P/caruso.png",
    categoria: "Pizzas",
  },
  {
    id: "15",
    nombre: "Cuatro Quesos",
    precio: "3150",
    descripcion: "Pizza de Muzzarella, Roquefort, Provolone, Provoleta, Morrones, Salsa de Tomate, Condimentos y Aceitunas Verdes.",
    imagen: "https://i.ibb.co/MV4TzFG/Fugazza.png",
    categoria: "Pizzas",
  },
  {
    id: "16",
    nombre: "Dati (Palmitos)",
    precio: "3500",
    descripcion: "Pizza de Muzzarella, Jamón al Natural, Morrones, Huevo Duro, Palmitos, Salsa Golf, Salsa de Tomate, Condimentos y Aceitunas Verdes.",
    imagen: "https://i.ibb.co/Hz8nZ6c/dati.png",
    categoria: "Pizzas",
  },
  {
    id: "17",
    nombre: "Espinaca",
    precio: "2450",
    descripcion: "Pizza de Muzzarella, Espinaca, Provolone, Morrones, Huevo Duro, Salsa de Tomate, Condimentos y Aceitunas Verdes.",
    imagen: "https://i.ibb.co/zGT0DBw/espinaca.png",
    categoria: "Pizzas",
  },
  {
    id: "18",
    nombre: "Pizza de Humita",
    precio: "2300",
    descripcion: "Pizza de Muzzarella, Humita, Provolone, Morrones, Salsa de Tomate, Condimentos y Aceitunas Verdes.",
    imagen: "https://i.ibb.co/MV4TzFG/Fugazza.png",
    categoria: "Pizzas",
  },
  {
    id: "19",
    nombre: "Jamon Al Roquefort",
    precio: "2600",
    descripcion: "Pizza de Muzzarella, Jamon Natural, Roquefort, Morrones, Salsa de Tomate, Condimentos y Aceitunas Verdes.",
    imagen: "https://i.ibb.co/MV4TzFG/Fugazza.png",
    categoria: "Pizzas",
  },
  {
    id: "20",
    nombre: "Panceta",
    precio: "2450",
    descripcion: "Pizza de Muzzarella, Panceta, Morrones, Salsa de Tomate, Condimentos y Aceitunas Verdes.",
    imagen: "https://i.ibb.co/rm7RtZm/panceta.png",
    categoria: "Pizzas",
  },
  {
    id: "21",
    nombre: "Pizzaiola",
    precio: "1300",
    descripcion: "Pizza de Muzzarella, Morrones, Salsa de Tomate, Tomate en Rodajas, Condimentos y Aceitunas Verdes. (sin Quesos)",
    imagen: "https://i.ibb.co/172wtTm/pizzaiola.png",
    categoria: "Pizzas",
  },
  {
    id: "22",
    nombre: "Provoleta",
    precio: "2500",
    descripcion: "Masa Casera, Cebolla, Muzzarella y Condimentos.",
    imagen: "https://i.ibb.co/MV4TzFG/Fugazza.png",
    categoria: "Pizzas",
  },
  {
    id: "23",
    nombre: "Roquefort",
    precio: "2500",
    descripcion: "Pizza de Muzzarella, Roquefort, Morrones, Salsa de Tomate, Condimentos y Aceitunas Verdes.",
    imagen: "https://i.ibb.co/hdNSLLK/roquefort.png",
    categoria: "Pizzas",
  },
  {
    id: "24",
    nombre: "Rucula",
    precio: "3050",
    descripcion: "Pizza de Muzzarella, Rucula, Jamon Crudo, Parmesano, Salsa de Tomate, Condimentos y Aceitunas Verdes.",
    imagen: "https://i.ibb.co/TqwDQy6/rucula.png",
    categoria: "Pizzas",
  },
  {
    id: "25",
    nombre: "Super Napolitana",
    precio: "2500",
    descripcion: "Pizza de Muzzarella, Tomate en Rodajas, Jamon Natural, Morrones, Huevo, Salsa de Tomate, Condimentos y Aceitunas Verdes.",
    imagen: "https://i.ibb.co/VVP5qCV/supernapo.png",
    categoria: "Pizzas",
  },
  {
    id: "26",
    nombre: "Super Provolone",
    precio: "2450",
    descripcion: "Pizza de Muzzarella, Queso Provolone, Jamon Natural, Morrones, Salsa de Tomate, Condimentos y Aceitunas Verdes.",
    imagen: "https://i.ibb.co/MV4TzFG/Fugazza.png",
    categoria: "Pizzas",
  },
  {
    id: "27",
    nombre: "Rucula Sin Jamon",
    precio: "2800",
    descripcion: "Pizza de Muzzarella, Rucula, Parmesano, Salsa de Tomate, Condimentos y Aceitunas Verdes.",
    imagen: "https://i.ibb.co/MV4TzFG/Fugazza.png",
    categoria: "Pizzas",
  },
  {
    id: "28",
    nombre: "Muzza Con Huevo",
    precio: "2000",
    descripcion: "Pizza de Muzzarella, Huevo Duro, Salsa de Tomate, Condimentos y Aceitunas Verdes.",
    imagen: "https://i.ibb.co/MV4TzFG/Fugazza.png",
    categoria: "",
  },
  {
    id: "29",
    nombre: "Calzone de Anana",
    precio: "3300",
    descripcion: "Muzzarella, Anana, Cerezas al Maraschino, Jamon Natural y Condimentos.",
    imagen: "https://i.ibb.co/hWnQ0XB/calzone-roquefort.png",
    categoria: "Calzones",
  },
  {
    id: "30",
    nombre: "Calzone Calabresa",
    precio: "2900",
    descripcion: "Muzzarella, Longaniza Calabresa, Jamon Natural, Morrones y Condimentos.",
    imagen: "https://i.ibb.co/931VdK8/calzone-calabresa.png",
    categoria: "Calzones",
  },
  {
    id: "31",
    nombre: "Calzone Capresse",
    precio: "2900",
    descripcion: "Muzzarella, Jamon Natural, Morrones, Tomate en rodajas, Albahaca y Condimentos.",
    imagen: "https://i.ibb.co/hWnQ0XB/calzone-roquefort.png",
    categoria: "Calzones",
  },
  {
    id: "32",
    nombre: "Calzone Dati (Palmitos)",
    precio: "3600",
    descripcion: "Muzzarella, Jamon Natural, Morrones, Huevo Duro, Palmitos, Salsa Golf y Condimentos.",
    imagen: "https://i.ibb.co/hWnQ0XB/calzone-roquefort.png",
    categoria: "Calzones",
  },
  {
    id: "33",
    nombre: "Calzone Super Espinaca",
    precio: "3100",
    descripcion: "Muzzarella, Huevo Duro, Jamon Natural, Pollo, Espinaca, Salsa Blanca, Morrones y Condimentos. (Tamien version Vegetariana.)",
    imagen: "https://i.ibb.co/hWnQ0XB/calzone-roquefort.png",
    categoria: "Calzones",
  },
  {
    id: "34",
    nombre: "Calzone Espinaca Vegetariano",
    precio: "2950",
    descripcion: "Muzzarella, Huevo Duro, Espinaca, Salsa Blanca, Morrones y Condimentos.",
    imagen: "https://i.ibb.co/hWnQ0XB/calzone-roquefort.png",
    categoria: "Calzones",
  },
  {
    id: "35",
    nombre: "Calzone Napolitano",
    precio: "2890",
    descripcion: "Muzzarella, Jamon Natural, Morrones , Tomate en rodajas y Condimentos.",
    imagen: "https://i.ibb.co/T09kpV7/calzone-napo.png",
    categoria: "Calzones",
  },
  {
    id: "36",
    nombre: "Calzone Tradicional",
    precio: "2950",
    descripcion: "Muzzarella, Jamon Natural, Morrones y Condimentos.",
    imagen: "https://i.ibb.co/fxxg59S/calzone-tradicional.png",
    categoria: "Calzones",
  },
  {
    id: "37",
    nombre: "Empanada de Carne",
    precio: "220",
    descripcion: "Masa Casera, Carne, Cebolla, Huevo Duro y Condimentos.",
    imagen: "https://i.ibb.co/Xb886HZ/Empanada.png",
    categoria: "Empanadas",
  },
  {
    id: "38",
    nombre: "Empanada de Jamon y Queso",
    precio: "220",
    descripcion: "Masa Casera, Jamon Cocido, Muzzarella y Condimentos.",
    imagen: "https://i.ibb.co/Xb886HZ/Empanada.png",
    categoria: "Empanadas",
  },
  {
    id: "39",
    nombre: "Empanadas de Pollo",
    precio: "220",
    descripcion: "Masa Casera, pollo, Salsa Portuguesa y Condimentos.",
    imagen: "https://i.ibb.co/Xb886HZ/Empanada.png",
    categoria: "Empanadas",
  },
  {
    id: "40",
    nombre: "Empanada de Cebolla y Queso",
    precio: "220",
    descripcion: "Masa Casera, Cebolla, Muzzarella y Condimentos.",
    imagen: "https://i.ibb.co/Xb886HZ/Empanada.png",
    categoria: "Empanadas",
  },
  {
    id: "41",
    nombre: "Empanada Capresse",
    precio: "220",
    descripcion: "Masa Casera, Tomate Natural, Muzzarella, albahaca y Condimentos.",
    imagen: "https://i.ibb.co/Xb886HZ/Empanada.png",
    categoria: "Empanadas",
  },
  {
    id: "42",
    nombre: "Empanada de Verdura",
    precio: "220",
    descripcion: "Masa Casera, Espinaca, Muzzarella, Salsa Blanca y Condimentos.",
    imagen: "https://i.ibb.co/Xb886HZ/Empanada.png",
    categoria: "Empanadas",
  },
  {
    id: "43",
    nombre: "Empanada de Humita",
    precio: "220",
    descripcion: "Masa Casera, Humita, Choclo, Muzzarella y Condimentos.",
    imagen: "https://i.ibb.co/Xb886HZ/Empanada.png",
    categoria: "Empanadas",
  },
  {
    id: "44",
    nombre: "Calzone de Roquefort",
    precio: "3100",
    descripcion: "",
    imagen: "https://i.ibb.co/hWnQ0XB/calzone-roquefort.png",
    categoria: "Calzones",
  },
  {
    id: "45",
    nombre: "Calzone de Panceta",
    precio: "2900",
    descripcion: "",
    imagen: "https://i.ibb.co/B22G0jc/calzone-panceta.png",
    categoria: "Calzones",
  },
  {
    id: "46",
    nombre: "Coca Cola 2.25 L",
    precio: "480",
    descripcion: "Coca Cola 2.25 L",
    imagen: "https://i.ibb.co/mySCS3t/coca.png",
    categoria: "Bebidas",
  },
  {
    id: "47",
    nombre: "Coca Cola 1.5 L",
    precio: "380",
    descripcion: "Coca Cola 1.5 L",
    imagen: "https://i.ibb.co/mySCS3t/coca.png",
    categoria: "Bebidas",
  },
  {
    id: "48",
    nombre: "Sprite 2.25 L",
    precio: "480",
    descripcion: "Sprite 2.25 L",
    imagen: "https://i.ibb.co/KLbZg8T/sprite1-5.png",
    categoria: "Bebidas",
  },
  {
    id: "49",
    nombre: "Coca Ligth 2.25 L",
    precio: "480",
    descripcion: "Coca Ligth 2.25 L",
    imagen: "https://i.ibb.co/hVzvQbr/coca-light-225.png",
    categoria: "Bebidas",
  },
  {
    id: "50",
    nombre: "Coca Sin Azucar 2.25 L",
    precio: "480",
    descripcion: "Coca Sin Azucar 2.25 L",
    imagen: "https://i.ibb.co/sFJ8ymV/coca-zero.png",
    categoria: "Bebidas",
  },
  {
    id: "51",
    nombre: "Fanta 1.5 L",
    precio: "380",
    descripcion: "Fanta 1.5 L",
    imagen: "https://i.ibb.co/fdCVkgN/fanta-chica.png",
    categoria: "Bebidas",
  },
  {
    id: "52",
    nombre: "Fanta Sin Azucar 1.5 Litros",
    precio: "380",
    descripcion: "Fanta Sin Azucar 1.5 Litros",
    imagen: "https://i.ibb.co/x1pSSsr/fanta-sin-azucar15.png",
    categoria: "Bebidas",
  },
  {
    id: "53",
    nombre: "Sprite Zero 1.5L",
    precio: "380",
    descripcion: "Sprite Zero 1.5L",
    imagen: "https://i.ibb.co/BnF2w8y/spritechica.png",
    categoria: "Bebidas",
  },
  {
    id: "54",
    nombre: "Faina",
    precio: "190",
    descripcion: "Faina",
    imagen: "https://i.ibb.co/vX3XTVX/faina.png",
    categoria: "Faina",
  },
  {
    id: "55",
    nombre: "Calzone de Palmitos al Roquefort",
    precio: "3750",
    descripcion: "Muzzarella, Jamón Natural, Palmitos, Salsa Golf, Roquefort, Morrones, Salsa de Tomate, Condimentos y Aceitunas Verdes.",
    imagen: "https://i.ibb.co/hWnQ0XB/calzone-roquefort.png",
    categoria: "Calzones",
  },
  {
    id: "56",
    nombre: "Calzone Cuatro Quesos",
    precio: "3200",
    descripcion: "Muzzarella, Jamón Natural, Queso Provolone, Queso Provoleta, Queso Roquefort, Morrones, Salsa de Tomate y Condimentos.",
    imagen: "https://i.ibb.co/hWnQ0XB/calzone-roquefort.png",
    categoria: "Calzone",
  },
  {
    id: "57",
    nombre: "Fugazzetta Rellena al Roquefort",
    precio: "3000",
    descripcion: "Pizza Rellena con Jamón al Natural, Roquefort y Muzzarella. Cubierta de Cebolla, Morrones, Queso Provolone, Condimentos y Aceitunas.",
    imagen: "https://i.ibb.co/wK8NP6Q/fugazzeta-rellena-roquefort.png",
    categoria: "FuggazzettaRellena",
  },
  {
    id: "58",
    nombre: "Fugazzetta Rellena",
    precio: "2500",
    descripcion: "Pizza Rellena con Muzzarella y Cubierta de Cebolla, Condimentos y Aceitunas Verdes.",
    imagen: "https://i.ibb.co/KwY0c3Z/fugazzeta-rellena.png",
    categoria: "FuggazzettaRellena",
  },
  {
    id: "59",
    nombre: "Super Fugazzetta Rellena",
    precio: "2700",
    descripcion: "Pizza Rellena con Jamón al Natural y Muzzarella. Cubierta de Cebolla, Morrones, Queso Provolone, Condimentos y Aceitunas.",
    imagen: "https://i.ibb.co/zX60j9p/super-fugazzetta-rellena.png",
    categoria: "FuggazzettaRellena",
  },
  {
    id: "60",
    nombre: "Calzone de Cantimpalo",
    precio: "2090",
    descripcion: "Muzzarella, Cantimpalo, Jamón Natural, Morrones y Condimentos.",
    imagen: "https://i.ibb.co/hWnQ0XB/calzone-roquefort.png",
    categoria: "Calzone",
  },
  {
    id: "61",
    nombre: "Cantimpalo",
    precio: "1700",
    descripcion: "Pizza de Muzzarella, Cantimpalo, Morrones, Salsa de Tomate, Condimentos y Aceitunas Verdes.",
    imagen: "https://i.ibb.co/5nwsp55/cantimpalo.png",
    categoria: "Pizzas",
  },
  {
    id: "62",
    nombre: "Espárragos",
    precio: "1650",
    descripcion: "Pizza de Muzzarella, Espárragos, Queso Provolone, Morrones, Salsa de Tomate, Condimentos y Aceitunas Verdes.",
    imagen: "https://i.ibb.co/5nwsp55/cantimpalo.png",
    categoria: "Pizzas",
  },
  {
    id: "63",
    nombre: "Espárragos al Roquefort",
    precio: "1760",
    descripcion: "Pizza de Muzzarella, Espárragos, Queso Roquefort, Queso Provolone, Morrones, Salsa de Tomate, Condimentos y Aceitunas Verdes.",
    imagen: "https://i.ibb.co/5nwsp55/cantimpalo.png",
    categoria: "Pizzas",
  },
  {
    id: "64",
    nombre: "Calzone de Espárragos",
    precio: "2000",
    descripcion: "Muzzarella, Espárragos, Queso Provolone, Morrones, Salsa de Tomate, Condimentos y Aceitunas Verdes.",
    imagen: "https://i.ibb.co/hWnQ0XB/calzone-roquefort.png",
    categoria: "Calzones",
  },
  {
    id: "65",
    nombre: "Calzone de Espárragos al Roquefort",
    precio: "2800",
    descripcion: "Muzzarella, Espárragos, Queso Roquefort, Queso Provolone, Morrones, Salsa de Tomate, Condimentos y Aceitunas Verdes.",
    imagen: "https://i.ibb.co/hWnQ0XB/calzone-roquefort.png",
    categoria: "Calzones",
  }
];

export const gFetch = (id) => {
  return new Promise((resolve, reject) => {
    //acciones
    setTimeout(() => {
      resolve(id ? products.find((prod) => prod.id === id) : products);
      // reject(console.error(error))
    }, 200);
  });
};
